#!/usr/bin/env python3
"""Turn a WireGuard config downloaded from Mullvad into Molebridge's tunnel config,
or create a new PIA tunnel config.

Usage: tools/prepare-tunnel-config.py DOWNLOADED.conf [OUTPUT]
       tools/prepare-tunnel-config.py --pia [OUTPUT]

OUTPUT defaults to tunnel/wg_confs/mullvad.conf (tunnel/wg_confs/pia.conf with
--pia) and is written mode 0600. With --pia a new private key is generated and
the config has no address or peer: the applier registers the key with PIA and
sets both per region. An existing PIA config is never overwritten.
The downloaded server becomes the starting peer; the panel changes it later.
Only the private key, tunnel addresses and first peer are kept. The DNS line
is dropped on purpose (clients keep their own resolvers, see
docs/operations.md), and routing is handed to routing/10-exit-routing via
`Table = off` plus a default route in the exit table.

Prints no key material. Delete the downloaded file once this succeeds.
"""
from __future__ import annotations

import base64
import ipaddress
import secrets
import os
import re
import sys
import tempfile
from pathlib import Path

DEFAULT_OUTPUT = Path(__file__).resolve().parent.parent / 'tunnel' / 'wg_confs' / 'mullvad.conf'
DEFAULT_PIA_OUTPUT = DEFAULT_OUTPUT.with_name('pia.conf')
EXIT_TABLE = os.environ.get('EXIT_TABLE', '51821')


class ConfigError(ValueError):
    pass


def parse_wireguard_conf(text: str) -> dict:
    sections: dict = {'Interface': {}, 'Peer': {}}
    current = None
    for raw in text.splitlines():
        line = raw.split('#', 1)[0].strip()
        if not line:
            continue
        if line.startswith('[') and line.endswith(']'):
            name = line[1:-1].strip()
            if name == 'Peer' and sections['Peer']:
                current = None  # keep only the first peer
                continue
            current = name if name in sections else None
            continue
        if current and '=' in line:
            key, value = (part.strip() for part in line.split('=', 1))
            sections[current].setdefault(key, value)
    return sections


def require_key(value: str | None, field: str) -> str:
    try:
        if value and len(base64.b64decode(value, validate=True)) == 32:
            return value
    except ValueError:
        pass
    raise ConfigError(f'{field} is missing or is not a WireGuard key')


def build_tunnel_conf(text: str, table: str = EXIT_TABLE) -> str:
    conf = parse_wireguard_conf(text)
    iface, peer = conf['Interface'], conf['Peer']
    private_key = require_key(iface.get('PrivateKey'), 'Interface PrivateKey')
    public_key = require_key(peer.get('PublicKey'), 'Peer PublicKey')

    addresses = [a.strip() for a in iface.get('Address', '').split(',') if a.strip()]
    try:
        parsed = [ipaddress.ip_interface(a) for a in addresses]
    except ValueError:
        raise ConfigError('Interface Address is not valid') from None
    if not any(a.version == 4 for a in parsed):
        raise ConfigError('Interface Address has no IPv4 tunnel address')
    # What the routing image accepts (docs/configuration.md#the-tunnel-config):
    # one host address per family.
    if any(sum(a.version == v for a in parsed) > 1 for v in (4, 6)):
        raise ConfigError('Interface Address has more than one address in a family')
    if any(a.network.prefixlen != a.max_prefixlen for a in parsed):
        raise ConfigError('Interface Address must be host addresses (/32 and /128)')

    endpoint = peer.get('Endpoint', '')
    host, _, port = endpoint.rpartition(':')
    try:
        ipaddress.IPv4Address(host)
    except ValueError:
        raise ConfigError('Peer Endpoint must be an IPv4 address and port') from None
    if not re.fullmatch(r'[0-9]{1,5}', port) or not 1 <= int(port) <= 65535:
        raise ConfigError('Peer Endpoint port must be 1..65535')
    if not re.fullmatch(r'[1-9][0-9]{0,9}', table) or not 256 <= int(table) <= 2147483647:
        raise ConfigError('EXIT_TABLE must be an unreserved table number (256..2147483647)')

    has_v6 = any(a.version == 6 for a in parsed)
    post_up = f'ip route replace default dev %i table {table}'
    pre_down = f'ip route del default dev %i table {table}'
    if has_v6:
        post_up += f'; ip -6 route replace default dev %i table {table}'
        pre_down += f'; ip -6 route del default dev %i table {table}'

    return '\n'.join([
        '# Generated by tools/prepare-tunnel-config.py. Keep mode 0600; never commit.',
        '[Interface]',
        f'PrivateKey = {private_key}',
        f'Address = {", ".join(str(a) for a in parsed)}',
        'MTU = 1420',
        'Table = off',
        f'PostUp = {post_up}',
        f'PreDown = {pre_down}',
        '',
        '[Peer]',
        f'PublicKey = {public_key}',
        f'Endpoint = {host}:{port}',
        'AllowedIPs = 0.0.0.0/0' + (', ::/0' if has_v6 else ''),
        'PersistentKeepalive = 25',
        '',
    ])


def check_table(table: str) -> None:
    if not re.fullmatch(r'[1-9][0-9]{0,9}', table) or not 256 <= int(table) <= 2147483647:
        raise ConfigError('EXIT_TABLE must be an unreserved table number (256..2147483647)')


def new_private_key() -> str:
    """A Curve25519 private key as `wg genkey` makes it: random, clamped."""
    raw = bytearray(secrets.token_bytes(32))
    raw[0] &= 248
    raw[31] = (raw[31] & 127) | 64
    return base64.b64encode(bytes(raw)).decode()


def build_pia_conf(private_key: str, table: str = EXIT_TABLE) -> str:
    require_key(private_key, 'PrivateKey')
    check_table(table)
    # IPv4 only: PIA carries no IPv6, so IPv6 stays on the unreachable fallback.
    return '\n'.join([
        '# Generated by tools/prepare-tunnel-config.py --pia. Keep mode 0600; never commit.',
        '# No tunnel address or peer: the applier sets both when it registers this key with PIA.',
        '[Interface]',
        f'PrivateKey = {private_key}',
        'MTU = 1420',
        'Table = off',
        f'PostUp = ip route replace default dev %i table {table}',
        f'PreDown = ip route del default dev %i table {table}',
        '',
    ])


def write_private(path: Path, content: str) -> None:
    if not hasattr(os, 'fchmod'):
        raise ConfigError('Create the tunnel config on a POSIX host that supports mode 0600')
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix='.tmp-', dir=str(path.parent))
    try:
        with os.fdopen(fd, 'w') as f:
            os.fchmod(f.fileno(), 0o600)
            f.write(content)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


def main(argv: list) -> int:
    if len(argv) in (2, 3) and argv[1] == '--pia':
        output = Path(argv[2]) if len(argv) == 3 else DEFAULT_PIA_OUTPUT
        if output.exists():
            print(f'error: {output} exists; keep it, or remove it deliberately to make a new key', file=sys.stderr)
            return 1
        try:
            write_private(output, build_pia_conf(new_private_key()))
        except (OSError, ConfigError) as exc:
            print(f'error: {exc}', file=sys.stderr)
            return 1
        print(f'wrote {output} (mode 0600)')
        return 0
    if len(argv) not in (2, 3):
        print('\n'.join(__doc__.strip().splitlines()[3:5]), file=sys.stderr)
        return 2
    source = Path(argv[1])
    output = Path(argv[2]) if len(argv) == 3 else DEFAULT_OUTPUT
    try:
        content = build_tunnel_conf(source.read_text())
        write_private(output, content)
    except (OSError, ConfigError) as exc:
        print(f'error: {exc}', file=sys.stderr)
        return 1
    print(f'wrote {output} (mode 0600); delete {source} now')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv))
